<?php

//Experimenteer met strings en pas single & double quotes toe
//Experimenteer met string met variables met zowel single en double quotes
//Pas naast \n nog meer control characters toe
//Pas escaping toe in meerdere strings

$var = 'Variable';
//Single quotes example
echo 'This is a string with \'single quotes\' where we have to concatenate ' . $var .
      ' with  closing the \' \' and useing a .<br>' . PHP_EOL;
//Double quotes example
echo "In a string\040made with double \"\" you can use $var directly inside the \"quotes\".<br>\n";

//Pas Heredoc en Nowdoc toe in een bestand
//Heredoc example
$heredoc = <<<OCTOCAT
<pre>$var
....................................................................................................
...-------------::::::::::::::::-----------:::::::::::::::::::::::::::::::::::::::::::::::::::::-...
.../+++++++++++ommmmmmmmmmmmmmmmmhssyhhddmmmmmmmmmmmmmmmmmmmddddhhhdmmmmmmmmmmmmmmmmmhyyyyyyyyyy+...
.../+++++++++++smmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhyyyyyyyyyy+...
.../+++++++++++ymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyyyyyy+...
.../+++++++++++smmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhyyyyyyyyyy+...
.../+++++++++++ommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmyyyyyyyyyyy+...
.../++++++++++++ymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyyyyyyy+...
.../++++++++++osdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhyyyyyyyyyy+...
.../+++++++++ohmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyyyyy+...
.../++++++++ohmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyyyy+...
.../+++++++ohmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyyy+...
.../+++++++ymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdyyyyyy+...
.../++++++ommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhyyyyy+...
.../++++++ymmmmmmmmmmmmmmmmmmmmmmmddddddddddmmmmmmmmmmmmmmmmmddddddddddmmmmmmmmmmmmmmmmmmmdyyyyy+...
.../++++++hmmmmmmmmmmmmmmmmmmdhyso++////////++++oooooooooo+++////:::/osyyhhddmmmmmmmmmmmmmdyyyyy+...
.../++++++hmmmmmmmmmmmmmmmmhs+/-......................................-/syyyyhdmmmmmmmmmmmmyyyyy+...
.../++++++hmmmmmmmmmmmmmmdy+:-..:+/:--...........................-++/:---oyyyyyhmmmmmmmmmmdyyyyy+...
.../++++++ymmmmmmmmmmmmmhs/-..-s+-.-:/-.........................+o-..:/:--oyyyyyhmmmmmmmmmdyyyyy+...
.../++++++ymmmmmmmmmmmmds/-...y:..odmmmy:......................oo../hmmmh+-syyyyyhmmmmmmmmdyyyyy+...
.../++++++ommmmmmmmmmmmy+-...+o..ommmmmmd-....................-y..:mmmmmmm+:yyyyyydmmmmmmmhyyyyy+...
.../+++++++dmmmmmmmmmmdy+-...s:..dmmmmmmmo..................../o..ommmmmmmh.hyyyyyhmmmmmmmyyyyyy+...
.../+++++++smmmmmmmmmmmy+:...o:..hmmmmmmm+....................:o..+mmmmmmmy.hyyyyyhmmmmmmhyyyyyy+...
...+ssssssssdmmmmmmmmmmyo-...-o..:dmmmmmy......................s...ymmmmmd::hyyyyydmmmmmmhhhhhhho...
.../+oooooooodmmmmmmmmmds:..../:..-ohhy+.......................-+...+yhho--yyyyyyymmmmmmyyyyyyyy+...
...+ssssssssssdmmmmmmmmmho-....--..................+ys-..........:......./yyyyyyydmmmmmhhhhhhhhho...
.../++++++++++ohmmmmmmmmmho:.......................odh:............-:/+oyyyyyyyydmmmmdyyyyyyyyyy+...
.../+++++++++++oshmmmmmmmmdy+:-..................:.....:-.........-+syyyyyyyyyhmmmmdhyyyyyyyyyyy+...
.../+++++++++++++oshmmmmmmmmdhs+/:-..............+y/::oh:......:/oyyyyyyyyyhhmmmmdhyyyyyyyyyyyyy+...
.../+++++++++++++++ooyhdmmmmmmmdhhyso++/::---.....-/++/---:/+osyyyyyyyyhhdmmmmdhyyyyyyyyyyyyyyyy+...
.../++++ooo+++++++++++oosyhdmmmmmmmmdddhhhhyyyssssssssssyyyyhhhhhhdddmmmmmdhhyyyyyyyyyyyyyyyyyyy+...
.../+++yddshhsso++++++++++ooosyyhdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhhyyyyyyyyyyyyyyyyyyyyyyyy+...
.../+++oyhdmhhmdho++++++++++++++oooooydmmmmmmmhsyhdhyshmmmmmmmmhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+...
.../+++++oohmmmmmds++++++++++++++++oymmmmmmmmmdo-/yo-oddyyyyhmmmdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+...
.../+++++++ohmmmmmdyo+++++++++++++ohmmmmmmmmmmmmy/ysymmysddysmmmmdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+...
.../++++++++osdmmmmmhso+++++++++++smmmmmmmmmmmmmmdhmmmmdsyysymmmmmhyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+...
.../sssssssssssmmmmmmmdhysssssssyhdmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhho...
...smmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmms...
...smmyyhmmhyymhyyyyyhmmhysyhdmmmmmhyhmmyydmdyyddyyyyyymmmmmmdyyyydmmmhyyyhdmmyyyyhhmmmdyyyyyymms...
...smmy+odmo+smy++oooymyooso+odmmmmy+ommo+ymh+odh++ooosmmmmmho+so+odmyooso+smmo+oooosdmh++ooosmms...
...smmdo+yh+odmy++dmmmmo+smhoohmmmmh+odd++sms+omh++ymmmmmmmms+omd++ymo+smy++hmo+omh++ymh++hmmmmms...
...smmmy+oo+smmy++dmmmms+ohmdmmmmmmdo+hy++omo+ymh++hmmmmmmmmo+ommsshm++smy++hmo+omd++smh++hmmmmms...
...smmmdo++odmmy++syhmmmsooymmmmmmmmo+ys+o+ho+hmh++syymmmmmmo+ommmmmm++smy++hmo+omm++smh++syymmms...
...smmmmy++smmmy++ooymmmmyo+sdmmmmmmy+ooos+s+ommh++ooommmmmmo+ommmmmm++smy++hmo+omm++smh++oosmmms...
...smmmmh++hmmmy++dmmmmmmmho+ommmmmmh+++sh+++smmh++ymmmmmmmmo+ommhhdm++smy++hmo+omd++smh++hmmmmms...
...smmmmh++hmmmy++dmmmdsshmh++hmmmmmmo++ymo++ymmh++hmmmmmmmmo+omm++ym++smy++hmo+omd++smh++hmmmmms...
...smmmmh++hmmmy++yyyhdo+sdy+ohmmmmmms++dms++dmmh++syyymmmmms+ohy+ohmo+ohs+odmo+oys+ohmh++syyhmms...
...smmmmhoohmmmyooooosmhoooooymmmmmmmyoommhoommmhoooooommmmmdsooooymmdsoooohmmoooooshmmhoooooomms...
...smmmmmmmmmmmmmmmmmmmmmdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmdddmmmmmmmmmmmmmmmmmmmmmms...
...-::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-...
....................................................................................................
</pre>
OCTOCAT;

echo $heredoc;

//Nowdoc example
$nowdoc = <<<'NOW'
<hr>Now $var is like that in nowdoc<br>\n.<hr>
NOW;

echo $nowdoc;

//Pas de volgende functies toe: strlen, strtr en beschrijf in comment wat er gebeurd
//Measuring the string length for $heredoc
echo 'Length of the ascii octocat image: ' . strlen($heredoc);

//Altering the $heredoc ascii image replacing m o and y with + = and *
$newCat = strtr($heredoc, 'moy', '+=*');
echo $newCat . '<br>' . PHP_EOL;

//Gebruik een string als array; print het middelste karakter van een string,
//overschrijf deze en print nogmaals
$string = "QWERTY";
echo $string[3] . '<br>' . PHP_EOL;
//Changing the 3th position to a small r
$string[3] = 'r';
echo $string . '<br>' . PHP_EOL;

//Vergelijk strings met elkaar, met de == operator en de === operator
//Using the == to compare a string with a int
if('1' == 1) {
  echo 'Cause of the use off == the operator finds this 1 and "1" are equal<br>' . PHP_EOL;
} else {
  //won't get here
  echo 'meh<br>' . PHP_EOL;
}

//Using the === to compare a string with a int
if('2' === 2) {
  //won't get here
  echo "meh<br>\n";
} else {
  echo 'Now it sees the difference between a int and a string cause we used === <br>' . PHP_EOL;
}

//TODO Vergelijk (sub)strings met elkaar met de volgende functies: strcmp, strcasecmp,
//substr_compare

//TODO Pas de volgende functies toe: strpos, strstr, stripos, stristr en beschrijf
// in comment wat er gebeurd.

//TODO Pas de volgende functies toe: strspn, strcspan, str_replace, substr_replace,
//str_irpleace, met zowel string als arrays. Beschrijf in comment wat er gebeurd.

//TODO Experimenteer met substrings extracting

//TODO Format strings voor meerdere talen, door de setlocale-method toe te passen

//TODO Format numbers voor meerdere talen met de number_format functie, en currency
//met de money_format functie

//TODO Pas de volgende functies toe: printf, sprintf, fprintf en beschrijf in comment wat er
//gebeurd

//TODO Parse formatted input door de volgende functie toe te passen: sscanf

//TODO Doorloop alle stappen op https://regexone.com/

//TODO Experimenteer nadat je de stappen hebt doorlopen op Regexone met de Perl
//Compatible Regular Expressions functies binnen PHP: preg_match, preg_match_all,
//preg_replace. Beschrijf wederom in comments wat er gebeurd.


?>
